### ISSUE TITLE
Income calc doesn't parse negative numbers

### ISSUE THREAD

**Issue by fuiru** [Forecaster/factoryidle_eta_plugin#1]
When the code goes through the 5 factory buttons, it does not properly handle negative values.

I don't have git, or else I'd try to do a proper commit/PR, but for now, the fix (looking at main.js):

line 206 should be 
`var operator_pattern = /\-?[\d.]*([a-zA-Z]*)/;`

lines 370, 372, and 373 should be removed (as it will then properly add a negative number).

**Comment by Forecaster** [comment]
You can fork, make changes and pullreq all on github.com for the record
